INSERT INTO stories (title, flavour_text, cover_photo, text, genre, author_id)
VALUES ('The Milkmaid and Her Pail', 'Do not count your chickens before they are hatched."', 'http://dummyimage.com/239x100.png/ff4444/ffffff', 'A Milkmaid had been out to milk the cows and was returning from the field with the shining milk pail balanced nicely on her head. As she walked along, her pretty head was busy with plans for the days to come. "This good, rich milk," she mused, "will give me plenty of cream to churn. The butter I make I will take to market, and with the money I get for it I will buy a lot of eggs for hatching. How nice it will be when they are all hatched and the yard is full of fine young chicks. Then when May day comes I will sell them, and with the money I''ll buy a lovely new dress to wear to the fair. All the young men will look at me. They will come and try to make love to me,—but I shall very quickly send them about their business!" As she thought of how she would settle that matter, she tossed her head scornfully, and down fell the pail of milk to the ground. And all the milk flowed out, and with it vanished butter and eggs and chicks and new dress and all the milkmaid''s pride.', 'fable', 2);

INSERT INTO stories (title, flavour_text, cover_photo, text, genre, author_id)
VALUES ('The Fox and the Pheasants', 'Too much attention to danger may cause us to fall victims to it.', 'http://dummyimage.com/239x100.png/ff4444/ffffff', 'One moonlight evening as Master Fox was taking his usual stroll in the woods, he saw a number of Pheasants perched quite out of his reach on a limb of a tall old tree. The sly Fox soon found a bright patch of moonlight, where the Pheasants could see him clearly; there he raised himself up on his hind legs, and began a wild dance. First he whirled ''round and ''round like a top, then he hopped up and down, cutting all sorts of strange capers. The Pheasants stared giddily. They hardly dared blink for fear of losing him out of their sight a single instant. Now the Fox made as if to climb a tree, now he fell over and lay still, playing dead, and the next instant he was hopping on all fours, his back in the air, and his bushy tail shaking so that it seemed to throw out silver sparks in the moonlight. By this time the poor birds'' heads were in a whirl. And when the Fox began his performance all over again, so dazed did they become, that they lost their hold on the limb, and fell down one by one to the Fox', 'fable', 3);

INSERT INTO stories (title, flavour_text, cover_photo, text, genre, author_id)
VALUES ('The Wolf in Sheep''s Clothing', 'The evil doer often comes to harm through his own deceit.', 'http://dummyimage.com/239x100.png/ff4444/ffffff', 'A certain Wolf could not get enough to eat because of the watchfulness of the Shepherds. But one night he found a sheep skin that had been cast aside and forgotten. The next day, dressed in the skin, the Wolf strolled into the pasture with the Sheep. Soon a little Lamb was following him about and was quickly led away to slaughter. That evening the Wolf entered the fold with the flock. But it happened that the Shepherd took a fancy for mutton broth that very evening, and, picking up a knife, went to the fold. There the first he laid hands on and killed was the Wolf.', 'fable', 2);

INSERT INTO stories (title, flavour_text, cover_photo, text, genre, author_id)
VALUES ('The Old Lion', 'It is cowardly to attack the defenseless, though he be an enemy.', 'http://dummyimage.com/239x100.png/ff4444/ffffff', 'A Lion had grown very old. His teeth were worn away. His limbs could no longer bear him, and the King of Beasts was very pitiful indeed as he lay gasping on the ground, about to die. Where now his strength and his former graceful beauty? Now a Boar spied him, and rushing at him, gored him with his yellow tusk. A Bull trampled him with his heavy hoofs. Even a contemptible Ass let fly his heels and brayed his insults in the face of the Lion.', 'fable', 4);
