INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count)
VALUES (20, 'To the Milk Man', 'Weary and heart sick, the youth gently released his burden and silently prepared a place of comfort as his last duty to the loved one. Gathering fallen pine needles, he made a soft cushion and tenderly lifted his old mother onto it. He wrapped her padded coat more closely about the stooping shoulders and with tearful eyes and an aching heart he said farewell.', 'https://static01.nyt.com/images/2020/04/26/multimedia/26athome-cover/26athome-cover-jumbo.jpg', 'The eyes of the old mother were not so dim but that they noted the reckless hastening from one path to another, and her loving heart grew anxious. Her son did not know the mountains many paths and his return might be one of danger, so she stretched forth her hand and snapping the twigs from brushes as they passed, she quietly dropped a handful every few steps of the way so that as they climbed, the narrow path behind them was dotted at frequent intervals with tiny piles of twigs. At last the summit was reached. Weary and heart sick, the youth gently released his burden and silently prepared a place of comfort as his last duty to the loved one. Gathering fallen pine needles, he made a soft cushion and tenderly lifted his old mother onto it. He wrapped her padded coat more closely about the stooping shoulders and with tearful eyes and an aching heart he said farewell.

The trembling mothers voice was full of unselfish love as she gave her last injunction. “Let not thine eyes be blinded, my son.” She said. “The mountain road is full of dangers. LOOK carefully and follow the path which holds the piles of twigs. They will guide you to the familiar path farther down.” The sons surprised eyes looked back over the path, then at the poor old, shriveled hands all scratched and soiled by their work of love. His heart broke within and bowing to the ground, he cried aloud: “oh, Honorable mother, your kindness breaks my heart! I will not leave you. Together we will follow the path of twigs, and together we will die!”', 1, 46);



INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count)
VALUES (30, 'To Icecream Queen', 'The entire province trembled with dread. The order must be obeyed yet who in all Shining could make a rope of ashes? One night, in great distress, the son whispered the news to his hidden mother.', 'https://static01.nyt.com/images/2020/06/21/multimedia/21AH-cover-Chapman/21AH-cover-Chapman-jumbo.jpg', 'Once more he shouldered his burden (how light it seemed now) and hastened down the path, through the shadows and the moonlight, to the little hut in the valley. Beneath the kitchen floor was a walled closet for food, which was covered and hidden from view. There the son hid his mother, supplying her with everything she needed, continually watching and fearing she would be discovered. Time passed, and he was beginning to feel safe when again the governor sent forth heralds bearing an unreasonable order, seemingly as a boast of his power. His demand was that his subjects should present him with a rope of ashes.

The entire province trembled with dread. The order must be obeyed yet who in all Shining could make a rope of ashes? One night, in great distress, the son whispered the news to his hidden mother. “Wait!” she said. “I will think. I will think” On the second day she told him what to do. “Make rope of twisted straw,” she said. “Then stretch it upon a row of flat stones and burn it on a windless night.” He called the people together and did as she said and when the blaze died down, there upon the stones, with every twist and fiber showing perfectly, lay a rope of ashes.', 1, 35);

INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count)
VALUES (20, 'Forget the Fox, Checkout The Fish With Feet', 'There is a well-authenticated story of a ship-load of sheep that was lost because an old ram jumped overboard, and all the rest followed him.', 'https://static01.nyt.com/images/2020/12/06/books/review/06Otherworldly-EL_MOHTAR/06Otherworldly-EL_MOHTAR-jumbo.jpg', 'Then the dogging and shrieking and hustling and tearing have to be gone through all over again. (This on a red-hot day, mind you, with clouds of blinding dust about, the yolk of wool irritating your eyes, and, perhaps, three or four thousand sheep to put through). The delay throws out the man who is counting, and he forgets whether he left off at 45 or 95. The dogs, meanwhile, have taken the first chance to slip over the fence and hide in the shade somewhere, and then there are loud whistlings and oaths, and calls for Rover and Bluey.', 2, 100);

INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count)
VALUES (2, 'Never trust a fox', 'Look before you leap.', 'https://static01.nyt.com/images/2020/12/06/books/review/06Otherworldly-EL_MOHTAR/06Otherworldly-EL_MOHTAR-jumbo.jpg', 'A Fox fell into a well, and though it was not very deep, he found that he could not get out again. After he had been in the well a long time, a thirsty Goat came by. The Goat thought the Fox had gone down to drink, and so he asked if the water was good. "The finest in the whole country," said the crafty Fox, "jump in and try it. There is more than enough for both of us." The thirsty Goat immediately jumped in and began to drink. The Fox just as quickly jumped on the Goat''s back and leaped from the tip of the Goat''s horns out of the well The foolish Goat now saw what a plight he had got into, and begged the Fox to help him out. But the Fox was already on his way to the woods "If you had as much sense as you have beard, old fellow," he said as he ran, "you would have been more cautious about finding a way to get out again before you jumped in.', 2, 86);

INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count, is_accepted)
VALUES (91, 'Too Late', 'Look before you leap.', 'https://static01.nyt.com/images/2020/12/06/books/review/06Otherworldly-EL_MOHTAR/06Otherworldly-EL_MOHTAR-jumbo.jpg', 'By this time the poor birds'' heads were in a whirl. And when the Fox began his performance all over again, so dazed did they become, that they lost their hold on the limb, and fell down one by one to the Fox. Afterwards, the Fox went out and looked for something else to eat. He found a grape tree.The bunch hung from a high branch, and the Fox had to jump for it. The first time he jumped he missed it by a long way. So he walked off a short distance and took a running leap at it, only to fall short once more. Again and again he tried, but in vain. Now he sat down and looked at the grapes in disgust. "What a fool I am," he said. "Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for." And off he walked very, very scornfully.', 2, 22, true);

INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count, is_accepted)
VALUES (40, 'The Zoo and the City of Monsters', 'It was when one of the Cernogratz family died here that the wolves came from far and near and howled at the edge of the forest just before the death hour.', 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fceciliarodriguez%2Ffiles%2F2019%2F04%2F1-2.jpg', '"It is not when any one dies in the castle that the howling is heard. It was when one of the Cernogratz family died here that the wolves came from far and near and howled at the edge of the forest just before the death hour. There were only a few couple of wolves that had their lairs in this part of the forest, but at such a time the keepers say there would be scores of them, gliding about in the shadows and howling in chorus, and the dogs of the castle and the village and all the farms round would bay and howl in fear and anger at the wolf chorus, and as the soul of the dying one left its body a tree would crash down in the park. That is what happened when a Cernogratz died in his family castle. But for a stranger dying here, of course no wolf would howl and no tree would fall. Oh, no."

There was a note of defiance, almost of contempt, in her voice as she said the last words. The well-fed, much-too-well dressed Baroness stared angrily at the dowdy old woman who had come forth from her usual and seemly position of effacement to speak so disrespectfully.

', 3, 43, true);

INSERT INTO contributions (contributor_id, title, flavour_text, chapter_photo_url, text, story_id, upvote_count, is_accepted)
VALUES (99, 'A man might befriend a wolf, even break a wolf, but no man could truly tame a wolf', 'It was when one of the Cernogratz family died here that the wolves came from far and near and howled at the edge of the forest just before the death hour.', 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fceciliarodriguez%2Ffiles%2F2019%2F04%2F1-2.jpg', 'olf left his lair one evening in fine spirits and an excellent appetite. As he ran, the setting sun cast his shadow far out on the ground, and it looked as if the wolf were a hundred times bigger than he really was. "Why," exclaimed the Wolf proudly, "see how big I am! Fancy me running away from a puny Lion! I''ll show him who is fit to be king, he or I." Just then an immense shadow blotted him out entirely, and the next instant a Lion struck him down with a single blow.', 3, 23, false);
