DROP TABLE IF EXISTS stories CASCADE;

CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  flavour_text VARCHAR(255) NOT NULL,
  cover_photo VARCHAR(255) NOT NULL,
  is_complete BOOLEAN NOT NULL DEFAULT FALSE,
  text TEXT NOT NULL,
  genre VARCHAR(255) NOT NULL,
  author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
